### ISSUE TITLE
Compilation error (std::unordered_set<std::filesystem::path>)

### ISSUE THREAD

**Issue by c52e** [qiutang98/flower#2]
Hi,

There is no standard std::hash<std::filesystem::path>. (https://stackoverflow.com/questions/51065244/is-there-no-standard-hash-for-stdfilesystempath).

**Comment by qiutang98** [comment]
Hi, c52e.
Sorry current I only test code in Visual Studio 22 MSVC compiler, maybe some other C++ compiler still don't support this feature.

**Comment by c52e** [comment]
Append
```c++
namespace std {
	template <>
	struct hash<std::filesystem::path> {
		std::size_t operator()(const std::filesystem::path& path) const {
			return hash_value(path);
		}
	};
}
```
to `util.h` works in Visual Studio 2019, but I don't know whether this will be a collision in Visual Studio 2022.

**Comment by qiutang98** [comment]
Thank u, I will test the code later.

**Comment by c52e** [comment]
Sorry it seems that VS2022 is correct and there should be a standard std::hash\<std::filesystem::path\>.
https://en.cppreference.com/w/cpp/filesystem/path/hash
https://cplusplus.github.io/LWG/issue3657

**Comment by qiutang98** [comment]
yes it is a C++ stl feature, but VS19 may still un-implement, and i already add your fix code when compiler under _MSC_VER 1930.

**Comment by c52e** [comment]
Thanks, it compiles on my machine.
