### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davidcralph** [qiutang98/flower#3]
Hello,

I was wondering what the license of this repository is, as there doesn't seem to be a LICENSE file anywhere? Adding one would make the rules regarding how things can be used much clearer, and would also help with additional contributions.

Thank you for your work on this project.

**Comment by qiutang98** [comment]
Hi, davidcralph, you re welcome.

The license is MIT or un-license, (maybe i should upload later), feel free to copy and share whatever you like, XD.

**Comment by davidcralph** [comment]
Much appreciated :)
